import Head from "next/head";
import styles from "../styles/Home.module.css";
import AudioPlayer from "../components/AudioPlayer";
import Header from "../components/Header";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Audio Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <AudioPlayer />
      </main>
    </div>
  );
}
